# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_historicalcategory_historicalpost_historicaltag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpost',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicalpost',
            name='pub_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Published'),
        ),
    ]
