# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20170601_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpost',
            name='slug',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
